language: ruby
rvm:
  - 2.4.1

cache: bundler

script:
  - bundle exec rake db:create db:migrate
  - bundle exec rake spec
  - bundle exec rubocop

services:
  - postgresql

before_script:
  - cp config/database.yml.example config/database.yml
    
    
