language: ruby
rvm:
  - 2.4.1

cache: bundler

script:
  - bundle exec rake db:create db:migrate
  - bundle exec rake spec
  - bundle exec rubocop
  - bundle exec reek
  - bundle exec brakeman
  - bundle exec rails_best_practices -e "db/migrate,vendor" .
  
services:
  - postgresql
  - redis-server

before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle exec sidekiq -d -L /tmp/sidekiq.log
  - sleep 1
